name: CI
on:
  pull_request:
  push:
  schedule:
    - cron: '11 5 1 * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1
    - name: Build and Test
      run: sbt -v +test
